default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: skincare-library-backend_development
  username: postgres
  password: skincare-lib
  host: localhost

test:
  <<: *development
  database: skincare-library-backend_test

production:
  url: <%= ENV['DATABASE_URL'] %>